useDotenv: true

service: poprox-kluver-recommender
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  versionFunctions: false
  region: ${opt:region, "us-east-1"}
  stage: ${opt:stage, "local"}
  memorySize: 2048 # 2gb
  timeout: 25
  architecture: x86_64

  iam:
    role:
      # Add statements to the IAM role to give permissions to Lambda functions
      statements:
        - Effect: Allow
          Action:
            - "logs:*"
          Resource: "*"

  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      poprox-recommender-kluver:
        path: "./"
        platform: linux/amd64

package:
  patterns:
    - "!venv/**"
    - "!models/**"
    - "!node_modules/**"
    - "!tests/**"
    - "**.py"
    - "**.html"

functions:
  generateRecommendationsKluver:
    image:
      name: poprox-recommender-kluver
    memorySize: 4096
    ephemeralStorageSize: 2048
    events:
      - http:
          path: /warmup
          method: get
      - http:
          path: /
          method: post

# What you need to do:
#  1. Go into AWS console
#  2. Go to the "quotas and limits" tool
#  3. Go to the api gateway limits
#  4. Find the maximum timeout in milliseconds, it should be 30000, bump it up.
#    * The more you bump it, the less likely an automtic approval is. Also, check with the team, it doesn't need to be bigger than the platform timeout.
#  5. Now go to serverless.yml and change all the `httpapi` to `http` as seen above in the event section
#  6. Now deploy it
#  7. Now go in, find the POST / endpoint in the api gateway tool.
#  8. Edit the integration request for this endpoint to have a larger timeout.
#  9. Edit the API as a whole to be a region API not an edge API.
#  10 . Redeploy, wait, and test.
